import turtle
t = turtle.Turtle()
npa = turtle.screensize(200,200)
t.speed(0)
t.pencolor("black")
ngang = int(input("nhập chiều ngang: "))
cao = int(input("nhập chiều cao: "))

def rectangle (hor,ver,col):
    t.pendown()
    t.pensize(5)
    t.fillcolor(col)
    t.begin_fill()
    for counter in range(1,3):
        t.forward(hor)
        t.right(90)
        t.forward(ver)
        t.right(90)
    t.end_fill()
    t.penup()
    t.forward(hor/3)
    t.right(90)
    t.forward(ver/3)
    t.left(90)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    for i in range(1,3):
        t.forward(hor/3)
        t.right(90)
        t.forward(ver/3)
        t.right(90)
    t.end_fill()
    t.penup()


def rectangle (hor,ver,col):
    t.pendown()
    t.pensize(2)
    t.fillcolor(col)
    t.begin_fill()
    for counter in range(1,3):
        t.forward(hor)
        t.right(90)
        t.forward(ver)
        t.right(90)
    t.end_fill()
    t.penup()
    t.forward(hor/3)
    t.right(90)
    t.forward(ver/3)
    t.left(90)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    for i in range(1,3):
        t.forward(hor/3)
        t.right(90)
        t.forward(ver/3)
        t.right(90)
    t.end_fill()
    t.penup()


def cuachinh (hor,ver,col):
    t.pendown()
    t.pensize(2)
    t.fillcolor(col)
    t.begin_fill()
    for counter in range(1,3):
        t.forward(hor)
        t.right(90)
        t.forward(ver)
        t.right(90)
    t.end_fill()
    t.penup()
    t.forward(hor/4)
    t.right(90)
    t.forward(ver/3)
    t.left(90)
    t.pendown()
    t.fillcolor("white")
    t.begin_fill()
    for i in range(1,3):
        t.forward(hor/2)
        t.right(90)
        t.forward(ver*2/3)
        t.right(90)
    t.end_fill()
    t.penup()
    t.forward(hor/4)
    t.right(90)
    t.pendown()
    t.forward(ver*2/3)
    t.penup()

rectangle (ngang,cao,"green")
t.goto(ngang,cao)
rectangle (ngang,cao,"red")
t.goto(ngang,0)
rectangle (ngang,cao,"blue")
t.goto(0,cao)
rectangle (ngang,cao,"pink")

t.goto(ngang*2,0)
cuachinh (ngang*3,cao,"black")

turtle.done()